# TCL File Generated by Component Editor 13.0sp1
# Wed Oct 28 12:11:54 PDT 2020
# DO NOT MODIFY


# 
# avm_audio_controller "Audio Controller" v1.0
# Heqing Huang 2020.10.28.12:11:54
# Avalon Memory Mapped Audio Controller for WM8731/WM8731L chip
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avm_audio_controller
# 
set_module_property DESCRIPTION "Avalon Memory Mapped Audio Controller for WM8731/WM8731L chip"
set_module_property NAME avm_audio_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property AUTHOR "Heqing Huang"
set_module_property DISPLAY_NAME "Audio Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avm_audio_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avm_audio_controller.v VERILOG PATH avm_audio_controller.v TOP_LEVEL_FILE
add_fileset_file audio_codec_transceiver.v VERILOG PATH audio_codec_transceiver.v
add_fileset_file audio_controller.v VERILOG PATH audio_controller.v
add_fileset_file audio_controller_csr.v VERILOG PATH ../csr/audio_controller_csr/rtl/audio_controller_csr.v
add_fileset_file avm_audio_controller.v VERILOG PATH avm_audio_controller.v
add_fileset_file dsync.v VERILOG PATH ../../common/rtl/dsync.v
add_fileset_file fifo.v VERILOG PATH ../../common/rtl/fifo.v
add_fileset_file fwft_fifo.v VERILOG PATH ../../common/rtl/fwft_fifo.v
add_fileset_file i2c_master.v VERILOG PATH ../../i2c_controller/rtl/i2c_master.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avm_audio_controller
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avm_audio_controller.v VERILOG PATH avm_audio_controller.v
add_fileset_file audio_codec_transceiver.v VERILOG PATH audio_codec_transceiver.v
add_fileset_file audio_controller.v VERILOG PATH audio_controller.v
add_fileset_file audio_controller_csr.v VERILOG PATH ../csr/audio_controller_csr/rtl/audio_controller_csr.v
add_fileset_file dsync.v VERILOG PATH ../../common/rtl/dsync.v
add_fileset_file fifo.v VERILOG PATH ../../common/rtl/fifo.v
add_fileset_file fwft_fifo.v VERILOG PATH ../../common/rtl/fwft_fifo.v
add_fileset_file i2c_master.v VERILOG PATH ../../i2c_controller/rtl/i2c_master.v


# 
# parameters
# 
add_parameter SYSCLK INTEGER 50 ""
set_parameter_property SYSCLK DEFAULT_VALUE 50
set_parameter_property SYSCLK DISPLAY_NAME SYSCLK
set_parameter_property SYSCLK WIDTH ""
set_parameter_property SYSCLK TYPE INTEGER
set_parameter_property SYSCLK UNITS None
set_parameter_property SYSCLK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYSCLK DESCRIPTION ""
set_parameter_property SYSCLK HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits SYMBOLS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avm_address address Input 5
add_interface_port s0 avm_read read Input 1
add_interface_port s0 avm_write write Input 1
add_interface_port s0 avm_writedata writedata Input 32
add_interface_port s0 avm_readdata readdata Output 32
add_interface_port s0 avm_select chipselect Input 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point i2c
# 
add_interface i2c conduit end
set_interface_property i2c associatedClock clock
set_interface_property i2c associatedReset ""
set_interface_property i2c ENABLED true
set_interface_property i2c EXPORT_OF ""
set_interface_property i2c PORT_NAME_MAP ""
set_interface_property i2c SVD_ADDRESS_GROUP ""

add_interface_port i2c i2c_SDA export Bidir 1
add_interface_port i2c i2c_SCL export Bidir 1


# 
# connection point audio_control
# 
add_interface audio_control conduit end
set_interface_property audio_control associatedClock clock
set_interface_property audio_control associatedReset ""
set_interface_property audio_control ENABLED true
set_interface_property audio_control EXPORT_OF ""
set_interface_property audio_control PORT_NAME_MAP ""
set_interface_property audio_control SVD_ADDRESS_GROUP ""

add_interface_port audio_control bclk export Output 1
add_interface_port audio_control mclk export Output 1
add_interface_port audio_control daclrc export Output 1
add_interface_port audio_control dacdat export Output 1
add_interface_port audio_control adclrc export Output 1
add_interface_port audio_control adcdat export Input 1


# 
# connection point adc_dac_user
# 
add_interface adc_dac_user conduit end
set_interface_property adc_dac_user associatedClock clock
set_interface_property adc_dac_user associatedReset ""
set_interface_property adc_dac_user ENABLED true
set_interface_property adc_dac_user EXPORT_OF ""
set_interface_property adc_dac_user PORT_NAME_MAP ""
set_interface_property adc_dac_user SVD_ADDRESS_GROUP ""

add_interface_port adc_dac_user dac_data_in export Input 32
add_interface_port adc_dac_user dac_data_wr export Input 1
add_interface_port adc_dac_user adc_data_out export Output 32
add_interface_port adc_dac_user adc_data_rd export Input 1
add_interface_port adc_dac_user dac_fifo_full export Output 1
add_interface_port adc_dac_user adc_fifo_empty export Output 1

