//////////////////////////////////////////////////////
//
// Driver for audio_controller CSR module
// Generated by Simple CSR Generator
// Created: 11/1/2020 18:4
//
//////////////////////////////////////////////////////


// =============================================
// Register: status, Address: 0x0
// =============================================
#define AUDIO_CONTROLLER__STATUS
#define AUDIO_CONTROLLER__STATUS_ADDR                       0x0

// Field: I2C_IDLE, Offset: 0, Size: 1
#define AUDIO_CONTROLLER__STATUS__I2C_IDLE__OFT             0
#define AUDIO_CONTROLLER__STATUS__I2C_IDLE__MASK            0x1
#define AUDIO_CONTROLLER__STATUS__I2C_IDLE__get(data) \
        ((data & AUDIO_CONTROLLER__STATUS__I2C_IDLE__MASK) >> AUDIO_CONTROLLER__STATUS__I2C_IDLE__OFT)
#define AUDIO_CONTROLLER__STATUS__I2C_IDLE__set(I2C_IDLE) \
        ((I2C_IDLE << AUDIO_CONTROLLER__STATUS__I2C_IDLE__OFT) & AUDIO_CONTROLLER__STATUS__I2C_IDLE__MASK)

// Field: DAC_FIFO_FULL, Offset: 1, Size: 1
#define AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__OFT        1
#define AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__MASK       0x2
#define AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__get(data) \
        ((data & AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__MASK) >> AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__OFT)
#define AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__set(DAC_FIFO_FULL) \
        ((DAC_FIFO_FULL << AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__OFT) & AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__MASK)

// Field: ADC_FIFO_EMPTY, Offset: 2, Size: 1
#define AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__OFT       2
#define AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__MASK      0x4
#define AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__get(data) \
        ((data & AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__MASK) >> AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__OFT)
#define AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__set(ADC_FIFO_EMPTY) \
        ((ADC_FIFO_EMPTY << AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__OFT) & AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__MASK)

#define AUDIO_CONTROLLER__STATUS__set(ADC_FIFO_EMPTY, DAC_FIFO_FULL, I2C_IDLE) (\
        AUDIO_CONTROLLER__STATUS__ADC_FIFO_EMPTY__set(ADC_FIFO_EMPTY) | \
        AUDIO_CONTROLLER__STATUS__DAC_FIFO_FULL__set(DAC_FIFO_FULL) | \
        AUDIO_CONTROLLER__STATUS__I2C_IDLE__set(I2C_IDLE))


// =============================================
// Register: ctrl, Address: 0x4
// =============================================
#define AUDIO_CONTROLLER__CTRL
#define AUDIO_CONTROLLER__CTRL_ADDR                         0x4

// Field: DAC_SEL, Offset: 0, Size: 1
#define AUDIO_CONTROLLER__CTRL__DAC_SEL__OFT                0
#define AUDIO_CONTROLLER__CTRL__DAC_SEL__MASK               0x1
#define AUDIO_CONTROLLER__CTRL__DAC_SEL__get(data) \
        ((data & AUDIO_CONTROLLER__CTRL__DAC_SEL__MASK) >> AUDIO_CONTROLLER__CTRL__DAC_SEL__OFT)
#define AUDIO_CONTROLLER__CTRL__DAC_SEL__set(DAC_SEL) \
        ((DAC_SEL << AUDIO_CONTROLLER__CTRL__DAC_SEL__OFT) & AUDIO_CONTROLLER__CTRL__DAC_SEL__MASK)

// Field: ADC_SEL, Offset: 1, Size: 1
#define AUDIO_CONTROLLER__CTRL__ADC_SEL__OFT                1
#define AUDIO_CONTROLLER__CTRL__ADC_SEL__MASK               0x2
#define AUDIO_CONTROLLER__CTRL__ADC_SEL__get(data) \
        ((data & AUDIO_CONTROLLER__CTRL__ADC_SEL__MASK) >> AUDIO_CONTROLLER__CTRL__ADC_SEL__OFT)
#define AUDIO_CONTROLLER__CTRL__ADC_SEL__set(ADC_SEL) \
        ((ADC_SEL << AUDIO_CONTROLLER__CTRL__ADC_SEL__OFT) & AUDIO_CONTROLLER__CTRL__ADC_SEL__MASK)

#define AUDIO_CONTROLLER__CTRL__set(ADC_SEL, DAC_SEL) (\
        AUDIO_CONTROLLER__CTRL__ADC_SEL__set(ADC_SEL) | \
        AUDIO_CONTROLLER__CTRL__DAC_SEL__set(DAC_SEL))


// =============================================
// Register: adc_data, Address: 0x8
// =============================================
#define AUDIO_CONTROLLER__ADC_DATA
#define AUDIO_CONTROLLER__ADC_DATA_ADDR                     0x8

// Field: DATA, Offset: 0, Size: 32
#define AUDIO_CONTROLLER__ADC_DATA__DATA__OFT               0
#define AUDIO_CONTROLLER__ADC_DATA__DATA__MASK              0xffffffff
#define AUDIO_CONTROLLER__ADC_DATA__DATA__get(data) \
        ((data & AUDIO_CONTROLLER__ADC_DATA__DATA__MASK) >> AUDIO_CONTROLLER__ADC_DATA__DATA__OFT)
#define AUDIO_CONTROLLER__ADC_DATA__DATA__set(DATA) \
        ((DATA << AUDIO_CONTROLLER__ADC_DATA__DATA__OFT) & AUDIO_CONTROLLER__ADC_DATA__DATA__MASK)

#define AUDIO_CONTROLLER__ADC_DATA__set(DATA) (\
        AUDIO_CONTROLLER__ADC_DATA__DATA__set(DATA))


// =============================================
// Register: dac_data, Address: 0xc
// =============================================
#define AUDIO_CONTROLLER__DAC_DATA
#define AUDIO_CONTROLLER__DAC_DATA_ADDR                     0xc

// Field: DATA, Offset: 0, Size: 32
#define AUDIO_CONTROLLER__DAC_DATA__DATA__OFT               0
#define AUDIO_CONTROLLER__DAC_DATA__DATA__MASK              0xffffffff
#define AUDIO_CONTROLLER__DAC_DATA__DATA__get(data) \
        ((data & AUDIO_CONTROLLER__DAC_DATA__DATA__MASK) >> AUDIO_CONTROLLER__DAC_DATA__DATA__OFT)
#define AUDIO_CONTROLLER__DAC_DATA__DATA__set(DATA) \
        ((DATA << AUDIO_CONTROLLER__DAC_DATA__DATA__OFT) & AUDIO_CONTROLLER__DAC_DATA__DATA__MASK)

#define AUDIO_CONTROLLER__DAC_DATA__set(DATA) (\
        AUDIO_CONTROLLER__DAC_DATA__DATA__set(DATA))


// =============================================
// Register: i2c_ctrl, Address: 0x10
// =============================================
#define AUDIO_CONTROLLER__I2C_CTRL
#define AUDIO_CONTROLLER__I2C_CTRL_ADDR                     0x10

// Field: I2C_ID, Offset: 0, Size: 7
#define AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__OFT             0
#define AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__MASK            0x7f
#define AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__get(data) \
        ((data & AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__MASK) >> AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__OFT)
#define AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__set(I2C_ID) \
        ((I2C_ID << AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__OFT) & AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__MASK)

// Field: DATA, Offset: 7, Size: 16
#define AUDIO_CONTROLLER__I2C_CTRL__DATA__OFT               7
#define AUDIO_CONTROLLER__I2C_CTRL__DATA__MASK              0x7fff80
#define AUDIO_CONTROLLER__I2C_CTRL__DATA__get(data) \
        ((data & AUDIO_CONTROLLER__I2C_CTRL__DATA__MASK) >> AUDIO_CONTROLLER__I2C_CTRL__DATA__OFT)
#define AUDIO_CONTROLLER__I2C_CTRL__DATA__set(DATA) \
        ((DATA << AUDIO_CONTROLLER__I2C_CTRL__DATA__OFT) & AUDIO_CONTROLLER__I2C_CTRL__DATA__MASK)

// Field: WRITE, Offset: 23, Size: 1
#define AUDIO_CONTROLLER__I2C_CTRL__WRITE__OFT              23
#define AUDIO_CONTROLLER__I2C_CTRL__WRITE__MASK             0x800000
#define AUDIO_CONTROLLER__I2C_CTRL__WRITE__get(data) \
        ((data & AUDIO_CONTROLLER__I2C_CTRL__WRITE__MASK) >> AUDIO_CONTROLLER__I2C_CTRL__WRITE__OFT)
#define AUDIO_CONTROLLER__I2C_CTRL__WRITE__set(WRITE) \
        ((WRITE << AUDIO_CONTROLLER__I2C_CTRL__WRITE__OFT) & AUDIO_CONTROLLER__I2C_CTRL__WRITE__MASK)

#define AUDIO_CONTROLLER__I2C_CTRL__set(WRITE, DATA, I2C_ID) (\
        AUDIO_CONTROLLER__I2C_CTRL__WRITE__set(WRITE) | \
        AUDIO_CONTROLLER__I2C_CTRL__DATA__set(DATA) | \
        AUDIO_CONTROLLER__I2C_CTRL__I2C_ID__set(I2C_ID))


