//////////////////////////////////////////////////////
//
// Driver for ps2 CSR module
// Generated by Simple CSR Generator
// Created: 11/1/2020 18:4
//
//////////////////////////////////////////////////////


// =============================================
// Register: data, Address: 0x0
// =============================================
#define PS2__DATA
#define PS2__DATA_ADDR                                      0x0

// Field: TX_FIFO, Offset: 0, Size: 8
#define PS2__DATA__TX_FIFO__OFT                             0
#define PS2__DATA__TX_FIFO__MASK                            0xff
#define PS2__DATA__TX_FIFO__get(data) \
        ((data & PS2__DATA__TX_FIFO__MASK) >> PS2__DATA__TX_FIFO__OFT)
#define PS2__DATA__TX_FIFO__set(TX_FIFO) \
        ((TX_FIFO << PS2__DATA__TX_FIFO__OFT) & PS2__DATA__TX_FIFO__MASK)

// Field: RX_FIFO, Offset: 8, Size: 8
#define PS2__DATA__RX_FIFO__OFT                             8
#define PS2__DATA__RX_FIFO__MASK                            0xff00
#define PS2__DATA__RX_FIFO__get(data) \
        ((data & PS2__DATA__RX_FIFO__MASK) >> PS2__DATA__RX_FIFO__OFT)
#define PS2__DATA__RX_FIFO__set(RX_FIFO) \
        ((RX_FIFO << PS2__DATA__RX_FIFO__OFT) & PS2__DATA__RX_FIFO__MASK)

#define PS2__DATA__set(RX_FIFO, TX_FIFO) (\
        PS2__DATA__RX_FIFO__set(RX_FIFO) | \
        PS2__DATA__TX_FIFO__set(TX_FIFO))


// =============================================
// Register: status, Address: 0x4
// =============================================
#define PS2__STATUS
#define PS2__STATUS_ADDR                                    0x4

// Field: TX_FIFO_FULL, Offset: 0, Size: 1
#define PS2__STATUS__TX_FIFO_FULL__OFT                      0
#define PS2__STATUS__TX_FIFO_FULL__MASK                     0x1
#define PS2__STATUS__TX_FIFO_FULL__get(data) \
        ((data & PS2__STATUS__TX_FIFO_FULL__MASK) >> PS2__STATUS__TX_FIFO_FULL__OFT)
#define PS2__STATUS__TX_FIFO_FULL__set(TX_FIFO_FULL) \
        ((TX_FIFO_FULL << PS2__STATUS__TX_FIFO_FULL__OFT) & PS2__STATUS__TX_FIFO_FULL__MASK)

// Field: RX_FIFO_EMPTY, Offset: 1, Size: 1
#define PS2__STATUS__RX_FIFO_EMPTY__OFT                     1
#define PS2__STATUS__RX_FIFO_EMPTY__MASK                    0x2
#define PS2__STATUS__RX_FIFO_EMPTY__get(data) \
        ((data & PS2__STATUS__RX_FIFO_EMPTY__MASK) >> PS2__STATUS__RX_FIFO_EMPTY__OFT)
#define PS2__STATUS__RX_FIFO_EMPTY__set(RX_FIFO_EMPTY) \
        ((RX_FIFO_EMPTY << PS2__STATUS__RX_FIFO_EMPTY__OFT) & PS2__STATUS__RX_FIFO_EMPTY__MASK)

#define PS2__STATUS__set(RX_FIFO_EMPTY, TX_FIFO_FULL) (\
        PS2__STATUS__RX_FIFO_EMPTY__set(RX_FIFO_EMPTY) | \
        PS2__STATUS__TX_FIFO_FULL__set(TX_FIFO_FULL))


