# TCL File Generated by Component Editor 13.0sp1
# Wed Nov 04 23:04:53 PST 2020
# DO NOT MODIFY


# 
# avm_ps2_controller "PS2 Controller" v1.0
# Heqing Huang 2020.11.04.23:04:53
# Avalon Memory Mapped PS2 Controller
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module avm_ps2_controller
# 
set_module_property DESCRIPTION "Avalon Memory Mapped PS2 Controller"
set_module_property NAME avm_ps2_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Heqing Huang"
set_module_property DISPLAY_NAME "PS2 Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avm_ps2_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avm_ps2_controller.v VERILOG PATH avm_ps2_controller.v TOP_LEVEL_FILE
add_fileset_file dsync.v VERILOG PATH ../../common/rtl/dsync.v
add_fileset_file fwft_fifo.v VERILOG PATH ../../common/rtl/fwft_fifo.v
add_fileset_file ps2_controller.v VERILOG PATH ps2_controller.v
add_fileset_file ps2_core.v VERILOG PATH ps2_core.v
add_fileset_file ps2_csr.v VERILOG PATH ../csr/ps2_csr/rtl/ps2_csr.v
add_fileset_file ps2_rx.v VERILOG PATH ps2_rx.v
add_fileset_file ps2_tx.v VERILOG PATH ps2_tx.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avm_ps2_controller
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avm_ps2_controller.v VERILOG PATH avm_ps2_controller.v
add_fileset_file dsync.v VERILOG PATH ../../common/rtl/dsync.v
add_fileset_file fwft_fifo.v VERILOG PATH ../../common/rtl/fwft_fifo.v
add_fileset_file ps2_controller.v VERILOG PATH ps2_controller.v
add_fileset_file ps2_core.v VERILOG PATH ps2_core.v
add_fileset_file ps2_csr.v VERILOG PATH ../csr/ps2_csr/rtl/ps2_csr.v
add_fileset_file ps2_rx.v VERILOG PATH ps2_rx.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avm_ps2_controller
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avm_ps2_controller.v VERILOG PATH avm_ps2_controller.v
add_fileset_file dsync.v VERILOG PATH ../../common/rtl/dsync.v
add_fileset_file fwft_fifo.v VERILOG PATH ../../common/rtl/fwft_fifo.v
add_fileset_file ps2_controller.v VERILOG PATH ps2_controller.v
add_fileset_file ps2_core.v VERILOG PATH ps2_core.v
add_fileset_file ps2_csr.v VERILOG PATH ../csr/ps2_csr/rtl/ps2_csr.v
add_fileset_file ps2_rx.v VERILOG PATH ps2_rx.v


# 
# parameters
# 
add_parameter SYSCLK INTEGER 50
set_parameter_property SYSCLK DEFAULT_VALUE 50
set_parameter_property SYSCLK DISPLAY_NAME SYSCLK
set_parameter_property SYSCLK TYPE INTEGER
set_parameter_property SYSCLK UNITS None
set_parameter_property SYSCLK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYSCLK HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits SYMBOLS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits SYMBOLS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 1
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avm_address address Input 3
add_interface_port s0 avm_select chipselect Input 1
add_interface_port s0 avm_read read Input 1
add_interface_port s0 avm_write write Input 1
add_interface_port s0 avm_writedata writedata Input 32
add_interface_port s0 avm_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point ps2
# 
add_interface ps2 conduit end
set_interface_property ps2 associatedClock ""
set_interface_property ps2 associatedReset ""
set_interface_property ps2 ENABLED true
set_interface_property ps2 EXPORT_OF ""
set_interface_property ps2 PORT_NAME_MAP ""
set_interface_property ps2 SVD_ADDRESS_GROUP ""

add_interface_port ps2 ps2_data_i export Input 1
add_interface_port ps2 ps2_data_w export Output 1
add_interface_port ps2 ps2_data_o export Output 1
add_interface_port ps2 ps2_clk_i export Input 1
add_interface_port ps2 ps2_clk_w export Output 1
add_interface_port ps2 ps2_clk_o export Output 1


# 
# connection point interrupt
# 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint s0
set_interface_property interrupt associatedClock clock
set_interface_property interrupt associatedReset reset
set_interface_property interrupt ENABLED true
set_interface_property interrupt EXPORT_OF ""
set_interface_property interrupt PORT_NAME_MAP ""
set_interface_property interrupt SVD_ADDRESS_GROUP ""

add_interface_port interrupt ps2_data_avail irq Output 1

